### ISSUE TITLE
Pages Field broken in Kirby 3.2

### ISSUE THREAD

**Issue by thathoff** [OblikStudio/kirby-link-field#6]
The pages field is broken in Kirby 3.2. When you try to select a page it just displays a dialog with the message “not found”. It seems to be related to the API endpoints injected into the Kirby Pages Component. You also get a 404 not found message in the console when it tries to load the pages.

**Comment by hdodov** [comment]
Yep, I can confirm. Link field reuses core functionality for the page and file link types. It seems that 3.2 has changed that. I'll look into it.

**Comment by hdodov** [comment]
@thathoff hey, I just published a new major version of the package. [Check](https://packagist.org/packages/oblik/kirby-link-field). When you install it, please let me know if things are running smoothly. Sorry for the inconvenience!

**Comment by thathoff** [comment]
Seems to work again! I already started looking into creating a pull request but that looks like quite a big change. Thank you very much for the quick fix.

**Comment by hdodov** [comment]
In version `3.2`, the exact parts of the Kirby API I was using have been separated from the native pages and files fields of Kirby. This allowed me to use the parts I needed directly, instead of loading the native fields and extracting the parts that I wanted, which this issue proved to be fragile.

**Comment by philipmarnef** [comment]
With 2.0.0 the link field is still broken for me. I have a couple of structure fields with nested link fields in them and every structure field after the first shows the error 't.split is not a function' instead of rendering the structure in the panel.
I'm on Kirby 3.2.2.

**Comment by hdodov** [comment]
@philipmarnef add some more info. What does the structure look like? Where does the error appear? A screencap of the console would be useful.

**Comment by philipmarnef** [comment]
I've been debugging for the past hour and it seems the link field is not the culprit, but something else in Kirby 3.2.2. Sorry!
